#ifndef CHAINWAY_RFID_TYPES_DESC_H
#define CHAINWAY_RFID_TYPES_DESC_H

#define UNKNOWN "Unknown"
#define RESERVE "Reserve"

const char *rfid_message_type_desc[] = {
  "Acquisition hardware version number",
  "Answer acquisition hardware version number",
  "Obtain the firmware version number",
  "Firmware version number of responses",
  "Acquisition module ID",
  "ID response acquisition module",
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  "Sets the transmit power",
  "Sets the transmit power response",
  "Get the current transmit power",
  "Get the current transmit power response",
  "Hopping Set",
  "Setting the answer hopping",
  "Gets the current device status hopping set",
  "Gets the current device settings hopping state response",
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  "Setting parameters Gen2",
  "Gen2 parameter setting response",
  "Gets the current parameter settings Gen2",
  "Gets the current Gen2 parameter setting response",
  "CW Setting",
  "CW Setting the answer",
  "Gets the current device settings CW",
  "Gets the current device settings CW answer",
  "Antenna Set",
  "Setting the answer antenna",
  "Get the current antenna device settings",
  "Get the current antenna set the answering device",
  "Regional settings",
  "Locale response",
  "Gets the locale",
  "Gets the locale response",
  "Set upInventory data area",
  "Set upInventory data areaReply",
  RESERVE,
  RESERVE,
  "Get Device current temperature",
  "Get the current temperature responsive device",
  UNKNOWN,
  UNKNOWN,
  "Setting the temperature protection value",
  "Setting the temperature protection value of the response",
  "Get temperature protection value",
  "Gets temperature protection setting values in the answer",
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  "An antenna working hours",
  "An antenna working time response",
  "Gets antenna working hours",
  "Obtain an antenna response time",
  "Multi_antenna work interval",
  "Multi_antenna work interval reply",
  "Obtain multi_antenna work interval",
  "Obtain multi_antenna work interval reply",
  "Recommended combinations of RF link provided",
  "Set the recommended combination of RF link reply",
  "Get recommended setting combination of RF link",
  "Get recommended a combination of RF link setting response",
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  "Setting FastID function",
  "Answer the setting FastID",
  "Get FastID functional status",
  "Get FastID functional status response",
  "Setting TagFocus function",
  "Answer the setting TagFocus",
  "Get TagFocus functional status",
  "Get TagFocus functional status response",
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  "Software reset",
  "Software reset response",
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  "Look for the label filter settings",
  "Find answer label filter settings",
  "Provided simultaneously read EPC or TIDOr EPC or TIDmode",
  "Set read simultaneously EPC or TID or EPC or TID mode response",
  "Get while reading the EPC or TIDOr EPC or TIDmode",
  "Get read simultaneously EPC or TID or EPC or TID mode response",
  "Reset",
  "Factory Reset response",
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  "To find a single label",
  "To find a single label reply",
  "Continuous find labels",
  "Continuous labels to find answer",
  "Read Data",
  "Read data response",
  "Write data",
  "Write data response",
  "Lock tag",
  "Lock tag replies",
  "Kill label",
  "Kill label reply",
  "Stop seeking continuous label",
  "Stop the continuous label to find answer",
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  RESERVE,
  "Block Write tag",
  "Block Write tag replies",
  "Block Erase Label",
  "Block Erase transponder tag",
  "Set command parameters QT",
  "Set QT command parameter response",
  "Get command parameter QT",
  "Get command parameter response QT",
  "QT read",
  "QT read answer",
  "QT writes",
  "QT write response",
  "Block Permalock operation",
  "Block Permalock operating answer",
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN,
  UNKNOWN
};


#endif//CHAINWAY_RFID_TYPES_DESC_H